# we use websolr in production.

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: WARNING

test:
  solr:
    hostname: localhost
    port: <%= ENV['TEST_SOLR_PORT'] || '8981' %>
    log_level: WARNING